### ISSUE TITLE
[Bug] Calendar doesn't work unless popover component is also added

### ISSUE THREAD

**Issue by jtackaberry** [templui/templui#378]
## Describe the issue

When I follow the example at https://templui.io/docs/components/calendar I get a blank calendar inline:

<img width="434" height="130" alt="Image" src="https://github.com/user-attachments/assets/a3443f82-0c51-4fb7-98bc-bdfb7b08ae46" />

This problem goes away when I explicitly add the popover component (`templui add popover`) and initialize the popover script in the base layout.  So I think ultimately the problem is perhaps a combination of a missing dependency (I'd have expected popover to be installed when running `templui add calendar`) and a missing step in the documentation to include the popover script initialization.

Relatedly, when I follow the datepicker example at https://templui.io/docs/components/date-picker I get a similar blank calendar in the popup:

<img width="410" height="137" alt="Image" src="https://github.com/user-attachments/assets/b542ca2f-cdae-41c2-ad2b-477f45fd7494" />

The solution here is to initialize the calendar script.  The calendar component is properly installed as a dependency when I do `templui add datepicker` so I think this is just a small documentation gap.

---

## Reproduction steps

Just follow the documentation linked above :)

---

## Environment

- templUI version: 0.91.0
- Go version: 1.25.0
- Templ version: 0.3.943
- Tailwind version: 4.1.12
- Browser (if relevant): Firefox 142

**Comment by axadrn** [comment]
Thanks for reporting this!

You were right – the DatePicker docs missed `calendar.js`. Fixed in **1e519d61c8b7d3cf58a3ff0a0be24e61a5ed6924**.

* **Calendar** works standalone with just `calendar.js` (no popover needed).
* **DatePicker** needs all three:

```
@datepicker.Script()
@calendar.Script()
@popover.Script()
```

This should fix the blank calendar issue.

**Comment by jtackaberry** [comment]
> Calendar works standalone with just calendar.js (no popover needed).

I still have this problem, but I'll open another issue for this and point to a complete example.
